### ISSUE TITLE
OS X Python 3.4 build not uploading?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/astroid-feedstock#3]
Appears the OS X Python 3.4 build is not uploading, but not erroring out either. However, the Python 2.7 and 3.5 builds went up fine. 😕 Restarting the Travis CI Python 3.4 build to see if we can remedy this.

cc-ing @pelson for awareness about this strange issue (especially in case it is not easily resolved).

**Comment by jakirkham** [comment]
Resolved by restarting. Not sure what the underlying issue was though.

**Comment by pelson** [comment]
xref: https://github.com/Anaconda-Platform/support/issues/60?

**Comment by jakirkham** [comment]
Maybe. Was thinking about that too. Though it was a bit surprising as the other builds with that issue actually errored out and had nasty long tracebacks. 

In this case, instead of contacting Anaconda.org twice like it normally does, it contacted Anaconda.org once and then did nothing. So it was looking more like other skipped upload cases. Fortunately restarting fixed it in this case.

**Comment by jakirkham** [comment]
Yep, I agree, @pelson. Was able to find proof in another case described in issue ( https://github.com/conda-forge/line_profiler-feedstock/issues/6 ).

This shows us another problem, which basically is Travis CI build are not failing when an upload fails. Have raised that as issue ( https://github.com/conda-forge/conda-smithy/issues/267 ).
